# Hazelcast Configuration
spring:
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
      config: classpath:hazelcast.xml
    cache-names:
      - buckets

bucket4j:
  enabled: true
  debug : true
  cache:
    cache-name: buckets
  filters:
    - cache-name: buckets
      url: /first(/|\?)?.*
      rate-limits:
        - expression: "@securityService.getClientIP(#this)"
          bandwidths:
            - capacity: 1
              time: 5
              unit: seconds
    - cache-name: buckets
      url: /second(/|\?)?.*
      rate-limits:
        - expression: "@securityService.getClientIP(#this)"
          bandwidths:
            - capacity: 2
              time: 5
              unit: seconds
